
[Gameplay]
	#When the player enters the Aether, they are given a Book of Lore and Golden Parachutes as starting loot
	"Gives starting loot on entry" = true
	#Ambrosium Shards can be eaten to restore a half heart of health
	"Ambrosium Shards are edible" = false
	#Determines the limit of the amount of Life Shards a player can consume to increase their health
	"Maximum consumable Life Shards" = 10
	#On world creation, the player is given an Aether Portal Frame item to automatically go to the Aether with
	"Gives player Aether Portal Frame item" = false
	#Determines whether the Sun Spirit's dialogue when meeting him should play through every time you meet him
	"Repeat Sun Spirit's battle dialogue" = true

[Loot]
	#Allows the Valkyrie Cape to spawn in the Silver Dungeon loot table
	"Valkyrie Cape in loot" = false
	#Allows the Golden Feather to spawn in the Silver Dungeon loot table
	"Golden Feather in loot" = true

["World Generation"]
	#Determines whether Pink Aerclouds should generate in the skies of the Aether along with other Aerclouds
	"Generate Pink Aerclouds" = false
	#Determines whether the Aether should generate Tall Grass blocks on terrain or not
	"Generate Tall Grass in the Aether" = false
	#Determines whether Holiday Trees should always be able to generate when exploring new chunks in the Aether
	#If true, this overrides 'generate_holiday_tree_seasonally'
	"Generate Holiday Trees always" = false
	#Determines whether Holiday Trees should be able to generate during the time frame of December and January when exploring new chunks in the Aether
	#Only works if 'generate_holiday_tree_always' is set to false
	"Generate Holiday Trees seasonally" = true

[Multiplayer]
	#Makes it so that only the server admin or anyone with permission level 4 can use the Sun Altar on a server
	"Only admins use Sun Altars" = true

[Modpack]
	#Prevents the Aether Portal from being created normally in the mod
	"Disables Aether Portal creation" = false
	#The Aether Portal can only be activated with an item tagged as a Skyroot Bucket
	"Aether Portals activate with Skyroot Buckets" = false
	#Removes eternal day so that the Aether has a normal daylight cycle even before defeating the Sun Spirit
	"Disables eternal day" = false

