placeSnowInBlock = true
snowGravity = true
snowAlwaysReplaceable = true
#Unavailable if TerraForged mod installed
snowAccumulationDuringSnowstorm = true
#Unavailable if TerraForged mod installed
snowAccumulationDuringSnowfall = false
#Unavailable if TerraForged mod installed
thinnerBoundingBox = true
snowMakingIce = true
snowOnIce = false
snowNeverMelt = false
snowMeltsInWarmBiomes = false
snowReduceFallDamage = true
replaceWorldFeature = true
sustainGrassIfLayerMoreThanOne = true
#If you want to uninstall this mod, you probably want to make snow-covered blocks back to normal via random tick.
retainOriginalBlocks = false
#9 = Unlimited
#Range: 1 ~ 9
snowAccumulationMaxLayers = 8
#Should snow melt if layers are more than 1
snowNaturalMelt = false
advancedBlockInteraction = true

