name = "Better Recipe Book"
filename = "brb-1.18.2-fabric-1.5.6.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/vWIaVOTE/versions/1.5.6-2/brb-1.18.2-fabric-1.5.6.jar"
hash-format = "sha1"
hash = "e480d8d552f46bc88dbe332a1fa6b02d61120e48"

[update]
[update.modrinth]
mod-id = "vWIaVOTE"
version = "f9dBgqlK"
