name = "Charmonium"
filename = "charmonium-fabric-1.18-4.0.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/bpii4Xsa/versions/4.0.0/charmonium-fabric-1.18-4.0.0.jar"
hash-format = "sha1"
hash = "6f4105f8e2191a1125ae25958228cbf0930508c0"

[update]
[update.modrinth]
mod-id = "bpii4Xsa"
version = "eGTFdJii"

[option]
optional = false
default = false
description = "Adds ambient sound and additional music. Configurable"