name = "Charm"
filename = "charm-fabric-1.18-4.1.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/pOQTcQmj/versions/4.1.0/charm-fabric-1.18-4.1.0.jar"
hash-format = "sha1"
hash = "81ce0b2c2ad345ecdade0c2ba4f4d5388e8dd0d2"

[update]
[update.modrinth]
mod-id = "pOQTcQmj"
version = "wnS9y56O"
