name = "Cull Less Leaves"
filename = "CullLessLeaves-1.0.0.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/iG6ZHsUV/versions/1.0.0/CullLessLeaves-1.0.0.jar"
hash-format = "sha1"
hash = "19559b8892f43cfd938a3900d9bec47baf51b767"

[update]
[update.modrinth]
mod-id = "iG6ZHsUV"
version = "ml8Zv0AV"
