name = "Item Filters (Old)"
filename = "item-filters-fabric-1802.2.7-build.21.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3725/922/item-filters-fabric-1802.2.7-build.21.jar"
hash-format = "sha1"
hash = "d484b55040854b3268cf67e3f99211b764b13b5f"

[update]
[update.curseforge]
file-id = 3725922
project-id = 438500
