name = "LambdaBetterGrass"
filename = "lambdabettergrass-1.2.3+1.18.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/2Uev7LdA/versions/1.2.3+1.18/lambdabettergrass-1.2.3%2B1.18.jar"
hash-format = "sha1"
hash = "f5bdcf5dde183ca6c5b8ee28ab6193c1a9ef390d"

[update]
[update.modrinth]
mod-id = "2Uev7LdA"
version = "CXzPYiJu"
