name = "Sodium Extra"
filename = "sodium-extra-0.4.4+mc1.18.2-build.39.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/PtjYWJkn/versions/mc1.18.2-0.4.4/sodium-extra-0.4.4%2Bmc1.18.2-build.39.jar"
hash-format = "sha1"
hash = "a171437b0a8df4ba89015eff4f97504220577f34"

[update]
[update.modrinth]
mod-id = "PtjYWJkn"
version = "9LvKUEYM"
