name = "Universal Graves"
filename = "graves-2.0.1+1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/yn9u3ypm/versions/2.0.1+1.18.2/graves-2.0.1%2B1.18.2.jar"
hash-format = "sha1"
hash = "9abd6e21850d85e46c51b53b496efadf52796e39"

[update]
[update.modrinth]
mod-id = "yn9u3ypm"
version = "uUtfyTnt"
